Task 1
AndrewPolyakov1/formal-lang-course pull request #1
Opened 2024-02-14 19:40 UTC by AndrewPolyakov1

2024-03-02 14:37 UTC, KubEF requested changes

2024-03-02 14:37 UTC, KubEF commented on .github/workflows/code_style.yml
> +          python -m pytest tests/
Сделайте запуск автотестов с помощью скрипта `python ./scripts/run_tests.py`. Сделайте отдельный файлик для своего CI

2024-03-03 13:50 UTC, AndrewPolyakov1 commented on .github/workflows/code_style.yml
> +          python -m pytest tests/
Исправил, добавил отдельный workflow для тестов

2024-03-03 17:07 UTC, KubEF commented
А где запуск автотестов?

2024-03-03 17:52 UTC, AndrewPolyakov1 commented
> А где запуск автотестов?

.github/workflows/test.yml
Или я не совсем понимаю о чем вы

2024-03-03 21:25 UTC, KubEF requested changes

2024-03-03 21:25 UTC, KubEF commented on .github/workflows/test.yml
> +          python -m pytest tests/
Ну, мы написали скриптик, который просили запускать `python ./scripts/run_tests.py`

2024-03-03 21:39 UTC, AndrewPolyakov1 commented on .github/workflows/test.yml
> +          python -m pytest tests/
Увидел, я думал поменял, наверное когда делал rebase в конфликтах не то выбрал

2024-03-04 07:58 UTC, KubEF approved these changes

2024-03-06 16:13 UTC, merged